inherit_from: configs/Replica_SenFuNet/replica.yaml
mapping:
  bound: [[-2, 7], [-10, 4.5], [-2.6, 3.5]]
  marching_cubes_bound: [[-2, 7], [-10, 4.5], [-2.6, 3.5]]
data:
  input_folder: Datasets/Replica_SenFuNet/frl_apartment_0/1
  output: output/Replica_SenFuNet/frl_apartment_0/1
