inherit_from: configs/Replica_SenFuNet/replica.yaml
mapping:
  bound: [[-5.5, 5.9], [-6.7, 5.4], [-4.7, 5.3]]
  marching_cubes_bound: [[-5.5, 5.9], [-6.7, 5.4], [-4.7, 5.3]]
data:
  input_folder: Datasets/Replica_SenFuNet/office_0/1
  output: output/Replica_SenFuNet/office_0/1
