inherit_from: configs/Replica_SenFuNet/replica.yaml
mapping:
  bound: [[-2.9, 7.9], [-5.2, 3.7], [-4.9, 2.7]]
  marching_cubes_bound: [[-2.9, 7.9], [-5.2, 3.7], [-4.9, 2.7]]
data:
  input_folder: Datasets/Replica_SenFuNet/room_2/1
  output: output/Replica_SenFuNet/room_2/1
